### DISCUSSION TITLE
Auto-resolution of FQDNs into IP address lists

### DISCUSSION THREAD

**Discussion by jbemmel** [aerleon/aerleon#375] [Ideas]
In the wake of the recent CrowdStrike outage I was playing with the idea to generate ACLs to detect presence of Falcon agents in a network:
```
#
# Crowdstrike Falcon FQDNs for servers
# Source: https://www.dell.com/support/kbdoc/en-us/000177899/crowdstrike-falcon-sensor-system-requirements
#

networks:
  
  FALCON_US_1:
    values:
      - fqdn: ts01-b.cloudsink.net
      - fqdn: lfodown01-b.cloudsink.net
      - fqdn: lfoup01-b.cloudsink.net
      - fqdn: falcon.crowdstrike.com
      - fqdn: assets.falcon.crowdstrike.com
      - fqdn: assets-public.falcon.crowdstrike.com
      - fqdn: api.crowdstrike.com
      - fqdn: firehose.crowdstrike.com

  FALCON_US_2:
    values:
      - fqdn: ts01-gyr-maverick.cloudsink.net
      - fqdn: lfodown01-gyr-maverick.cloudsink.net
      - fqdn: lfoup01-gyr-maverick.cloudsink.net
      - fqdn: falcon.us-2.crowdstrike.com
      - fqdn: assets.falcon.us-2.crowdstrike.com
      - fqdn: assets-public.us-2.falcon.crowdstrike.com
      - fqdn: api.us-2.crowdstrike.com
      - fqdn: firehose.us-2.crowdstrike.com

  FALCON:
    values:
      - name: FALCON_US_1
      - name: FALCON_US_2
 ```

However, when I reference this ```FALCON``` list in a policy, I get an error:
```
aerleon.lib.naming.EmptyDefinitionError: No IP addresses found for network: FALCON_US_1
```

Would it be possible to have an option to resolve FQDNs into IP addresses?

**Comment by ankenyr** [comment]
Sorry I don't look in issues often. It is an interesting idea but what exactly do you mean by "generate ACLs to detect presence of Falcon agents in a network"

If it is just to allow the resolution of fqdn to their IPs then it is an interesting idea. It would make ACL generation non-deterministic as a change to DNS would make two runs different. For people who like version control this could be a nightmare.

Maybe a better idea would be to have a way to update IPs in the yaml based on the DNS via a script and then generation of ACLs can be done after?
```
networks:
  
  FALCON_US_1:
    values:
      - fqdn: ts01-b.cloudsink.net
        - ip: 3.3.3.3/32
        - ip: 3.3.3.4/32
      - fqdn: lfodown01-b.cloudsink.net
        - ip: 4.4.4.4/32
        - ip 4.4.4.5/32
```
