### ISSUE TITLE
[Security Issue] Includes exposes file system that could be abused.

### ISSUE THREAD

**Issue by ankenyr** [aerleon/aerleon#211]
We wish to change how the includes work due to this issue.

Currently includes will allow you to insert a path to another file. This file then would be expanded and parsed. This can be done recursively up to a certain level. The issue comes from the ability to pass any file name in.

```
header {
  comment:: "this is a sample edge input filter that generates"
  comment:: "msmpc output formats."
  target:: msmpc edge-inbound mixed ingress
}

#include '/home/rob/.ssh/known_hosts'

```

```
aerleon.aclgen.ACLParserError: Error parsing policy file policies/pol/sample_msmpc.pol:
<class 'aerleon.lib.policy.ParseError'> ERROR on "1" (type INTEGER, line 7, Next 'NbB3Ot9izt/XVnBEX7BJJQF0cK4')
```

While this is not the full contents, this is information leaking and could be used to explore the file system of the server if the API was exposed.

The YAML files behave slightly better but still exposes the existence of a file. It requires that the file have the extension `.yaml` else it errors our

```
  File "/home/rob/aerleon/aerleon/lib/yaml.py", line 280, in process_terms
    raise PolicyTypeError(
aerleon.lib.yaml.PolicyTypeError: Policy include source /home/rob/foo.asdas must end in ".yaml". File=policies/pol/sample_arista_tp_yaml.yaml, Line=13.
```
If the file does exist, regardless of if the syntax is correct, it will continue with no error. The ability to know the existence of a `.yaml` file on the system would be possible with this though we do not believe the contents could be retrieved.

Our idea is that includes need to have a specific name rather than a path

```
include-name: common-denials
terms:
- name: deny-from-bogons
  comment: this is a sample edge input filter with a very very very long and
           multi-line comment that also has multiple entries.
  source-address: BOGON
  action: deny

- name: deny-from-reserved
  source-address: RESERVED
  action: deny

- name: deny-to-rfc1918
  destination-address: RFC1918
  action: deny
```

The name must be unique within the corpus of includes, duplicates would result in an error. Then instead of referring to a path you would refer to the name identifying the specific include.

```
    terms:
      - name: accept-ssh-requests
        source-address: INTERNAL
        destination-port: SSH
        protocol: tcp
        counter: ssh
        action: accept
      - include: "common-denials"
      - name: accept-ssh-replies
```

Feedback on this would be appreciated from the community.
