### ISSUE TITLE
Juniper SRX dns-name support rendering on address-books

### ISSUE THREAD

**Issue by jbotello7381** [aerleon/aerleon#253]
Juniper SRX, and maybe other platforms support to configure dns names (fqdn) in their rules.   In the case of Juniper SRX, this is supported under

```
jbotello@fwn1-lab1.jimbo.net# show | compare
[edit security zones security-zone Pub]
+     address-book {
+         address DNS {
+             dns-name myserver.jimbo.net;
+         }
+     }

[edit]
```

Currently, aerleon definitions->networks doesn't support address in form of fqdn.  

It seems the use of verbatim is not possible either, since is only supported on terms.  

In order to improve the range of aerleon Juniper SRX support, it would be important for aerleon support dns-names in the networks definitions.

I'm not sure what option would be more aligned to the aerleon design.

```
networks:
   MYNET:
        values:
             - address: 10.10.10.10
             - address: myserver.jimbo.net
```

or

```
networks:
   MYNET:
        values:
             - address: 10.10.10.10
             - dns-name: myserver.jimbo.net
```
or any other key name that could be more aligned to other platforms in general? for example, Palo Alto i believe it define it as `fqdn`

```
networks:
   MYNET:
        values:
             - address: 10.10.10.10
             - fqdn: myserver.jimbo.net
```
