### ISSUE TITLE
 Service Token names are ignored and application names are changed to match the policy names

### ISSUE THREAD

**Issue by acarter1-godaddy** [aerleon/aerleon#310]
Hello,

I have noticed the following issue when using Aerleon to generate `.srx` config files from yaml policy files. When the file is built, the names of the applications are changed to match the name of the policy, even though there is a service token name in use.

Because of this, applications are created more than once but with different names to match the policies they are in.

Please see the example below:

YAML file:
```
- name: test_policy
    source-address: SOME_NET01
    destination-port:
    - TEST_APP01
    protocol:
    - tcp
    action: accept

  TEST_APP01:
  - port: 6065
    protocol: tcp
```

Generates the following `.srx` file:

```
policy test_policy {
        match {
            source-address [ SOME_NET01 ];
            destination-address any;
            application test_policy-app;
        }
        then {
            permit;
        }


    application-set test_policy-app {
    application test_policy-app1;
}


    application test_policy-app1 {
        term t1 protocol tcp destination-port 6065;
    }
```

You can see that 
`TEST_APP01` has now become `test_policy-app1` instead

Please somebody take a look at this issue.

Thanks very much :) 
Adam

**Comment by acarter1-godaddy** [comment]
Please let me know if I can help in anyway with testing potential fixes . We have a wide range of SRX rules that I can test on 😄

**Comment by ankenyr** [comment]
hey @acarter1-godaddy 
Sorry for letting this one linger. The desire here is for the policies to match closer to the name of the service, in this case `TEST_APP01` rather than the be named after the policy and incrementing a counter?

Is this something you or someone at Godaddy would want to take a stab at?

**Comment by acarter1-godaddy** [comment]
Hi Rob! 
Yeah that's right, we want the app name to reflect the service token name rather than the policy name as we were getting the same service appearing multiple times under different names because they were dependant on policy names.

We did already try taking a look into it but, unfortunately, couldn't get to the bottom of it

**Comment by ankenyr** [comment]
Just wanted to give an update. This change requires changes to naming.py which affects everything. I am trying to make it backwards compatible. I am updating all tests to use a real `naming.Naming` object and doing `self.naming._ParseLine` to create real objects rather than mocks. This however has in a few cases shown some bugs in the code. Seems that when you do not have strong typing and you do not return the right thing in a mock, you end up with bad code. Who would have thought?
In either case this is being worked on and the improvements will help a lot of other modules in the code base.

**Comment by acarter1-godaddy** [comment]
Hey @ankenyr 

Thanks very much for working on this issue 😄 Do you have any update about the progress at all?

We are weighing up the potential to write some temporary code to alter the generated config after the fact to have the correct application names. Then when the fix is out, just use pure aerleon again

**Comment by ankenyr** [comment]
Hi Adam!
I am so sorry, life had gotten in the way for a while. Let me take a look this afternoon and get back to you.

**Comment by ankenyr** [comment]
Refreshed myself on this. The idea was to use a [PPP class](https://github.com/aerleon/aerleon/blob/main/aerleon/lib/port.py#L40) more and pass ports in as objects. I wrote up about 500 lines before getting pulled away. I pushed the PR out so you can see the progress made so far. I believe there are still some missing pieces so I will review it and update more as I make progress here.

**Comment by acarter1-godaddy** [comment]
No worries Rob :) Thanks very much for taking a look into it again and thank you for the update!

**Comment by ankenyr** [comment]
Hi @acarter1-godaddy I have updated the code locally to allow for PPP to be used everywhere. This gives generators access to the service token that the port number and protocol came from.

The next step is to change how JuniperSRX works itself but I am having a bit of an issue.

Right now we create an application per rule, which works but there are some issues.

If we have two rules in a policy that reference the same port/protocol, for example SSH, but one uses it as a source-port and another uses it as a destination-port, there will be a conflict. The application would be named SSH for both and one would be overwritten. We could append a direction for the application to be more specific.

When we have a term that references multiple ports will it use an application set named after the rule still?

When we have a term that references only one port, will it use the application directly rather than an application set?

If two rules use a set, should those be deduplicated or should they continue to have their own unique named sets?

**Comment by acarter1-godaddy** [comment]
**If we have two rules in a policy that reference the same port/protocol, for example SSH, but one uses it as a source-port and another uses it as a destination-port, there will be a conflict. The application would be named SSH for both and one would be overwritten. We could append a direction for the application to be more specific.**

Appending "src" and "dst" to them could be a good solution for example:

```
application APP-BOOTPS {
    description "MS Active Directory - BOOTPS";
    term t1 protocol udp destination-port 67;
}
application APP-BOOTPS {
    description "MS Active Directory - BOOTPS";
    term t1 protocol udp source-port 67;
}

Can become - 
application APP-BOOTPS-dst {
    description "MS Active Directory - BOOTPS";
    term t1 protocol udp destination-port 67;
}
application APP-BOOTPS-src {
    description "MS Active Directory - BOOTPS";
    term t1 protocol udp source-port 67;
}
```
---

**When we have a term that references multiple ports will it use an application set named after the rule still?**

When a term uses multiple ports, it should be named after the service token defined:

so this service token and policy pair:

```
- name: allow-domainbox-dc
    description: RITM2104222
    source-address:
    - LDS-DOMAIN-CONTROLLERS
    destination-address:
    - DOMAINBOX-NET11
    destination-port:
    - kerberos-secured
    protocol:
    - udp
    - tcp
    action: accept
    logging: true

services:
  kerberos-secured:
    - port: 88
      protocol: tcp
    - port: 88
      protocol: udp
    - port: 464
      protocol: tcp
    - port: 464
      protocol: udp
```

It should use the token name:
```
    application kerberos-secured {
        term t1 protocol tcp destination-port 88;
        term t2 protocol udp destination-port 88;
        term t3 protocol tcp destination-port 464;
        term t4 protocol udp destination-port 464;
    }

policy ALLOW-DOMAINBOX-DC {
    match {
        source-address LDS-DOMAIN-CONTROLLERS;
        destination-address DOMAINBOX-NET11;
        application kerberos-secured;
    }
    then {
        permit;
        log {
            session-close;
        }
    }
}
```
Then, if a policy references more applications, then the configuration should reference each application or application set that is used rather than creating a new one and naming it after the policy

---

**When we have a term that references only one port, will it use the application directly rather than an application set?**

Yes, see example in previous question 

---
**If two rules use a set, should those be deduplicated or should they continue to have their own unique named sets?**

Each application and application-set should be unique - If 2 rules use the same application set then they should both point to the same application-set

e.g.

you have an application called "salt"
```
term t1 protocol tcp destination-port 4505-4506;
```
If 2 policies refernce that application, they should both point towards that application name. It should not be named after a policy name
```
policy RECOMM-SALTPROXY
match {
    source-address [ ADDRESS1 ADDRESS2 ];
    destination-address ADDRESS 3;
    application [ salt, junos-https ];
}
then {
    permit;
    log {
        session-close;
    }
}

policy ALLOW-HEG-SALTPROXY
match {
    source-address ADDRESS 4 ;
    destination-address ADDRESS 5 ;
    application salt;
}
then {
    permit;
    log {
        session-close;
    }
}
```
The YAML files for this would look like:

Policy yaml:
```
filters:
- header:
    targets:
      srx: from-zone ZONE1 to-zone ZONE2
    comment: auto generated ACL - manual changes will be overwritten
  terms:
	  - name: recomm-saltproxy
	    source-address:
	    - ADDRESS1
	    - ADDRESS2
	    destination-address:
	    - ADDRESS3
	    destination-port:
	    - salt
	    - junos-https
	    protocol:
	    - tcp
	    action: accept
	    logging: true

	  - name: allow-heg-saltproxy
	    source-address:
	    - ADDRESS4
	    destination-address:
	    - ADDRESS5
	    destination-port:
	    - salt
	    protocol:
	    - tcp
	    action: accept
	    logging: true
```
services yaml:
```
services:
	salt:
  	- port: 4505-4506
      protocol: tcp
```

network yaml: 
```
networks:
  ADDRESS1:
    values:
    - address: 1.1.1.1/32
  ADDRESS2:
    values:
    - address: 2.2.2.2/32
  ADDRESS3:
    values:
    - address: 3.3.3.3/32
```
    and so on 

---

Overall, we would like it so that the final configuration uses the names provided in the service and network tokens rather than policy names. This is how aerleon works for Arista, Juniper, and cisco switches/routers. The current setup makes it almost impossible to get information from the firewall itself, all descriptive names are erased. an example of this can be seen below within the other issue mentioned

Additionally, every update of a network token in the network definition file is creating huge differences due to the ordering of the IP addresses 

e.g.

generated file before change:
```
                address WOEPUPPET-MCS-INT_0 92.xxx.xxx.xxx/32;
                address WOEPUPPET-MCS-INT_1 148.xxx.xxx.xxx/32;
                address WOEPUPPET-MCS-INT_2 208.xxx.xxx.xxx/32;
                address WOEPUPPET-MCS-INT_3 216.xxx.xxx.xxx/32;
```
network token before change:
```
  WOEPUPPET-MCS-INT:
    values:
    - WOEPUPPET-MCS-PHX3
    - WOEPUPPET-MCS-SIN2
    - WOEPUPPET-MCS-SXB1
    - CA-WOEPUPPET-MCS-PHX3
```

Change:
```
  NEW-TEST-NETWORK:
    values:
    - address: 2.2.2.2/32

  WOEPUPPET-MCS-INT:
    values:
    - WOEPUPPET-MCS-PHX3
    - WOEPUPPET-MCS-SIN2
    - WOEPUPPET-MCS-SXB1
    - CA-WOEPUPPET-MCS-PHX3
    - NEW-TEST-NETWORK  <-------add new network that has ip address lower than 92.204.80.5/32
```

New generated config:
```
                address WOEPUPPET-MCS-INT_0 2.2.2.2/32;
                address WOEPUPPET-MCS-INT_1 92.xxx.xxx.xxx/32;
                address WOEPUPPET-MCS-INT_2 148.xxx.xxx.xxx/32;
                address WOEPUPPET-MCS-INT_3 208.xxx.xxx.xxx/32;
                address WOEPUPPET-MCS-INT_4 216.xxx.xxx.xxx/32;
```


As you can see, by adding 1 address, all existing address names have been changed. We have address-sets that have 400+ addresses so this will create unnecessary confusion for adding 1 IP address.
