### ISSUE TITLE
Allow for include of entire policies as an include.

### ISSUE THREAD

**Issue by ankenyr** [aerleon/aerleon#325]
https://aerleon.slack.com/archives/C042MD2SLRX/p1689694063955869 for more context

The original intention was for includes to be sets of terms and used for templating. In Capirca there was no limit on the expansion and so a whole policy file could be expanded.

This unintended feature has been discovered and is in use. This however was broken in Aerleon due to not realizing it was possible.

We would like to support this as a feature.

A yaml file should allow for something like
```
filters:
  - header:
    targets:
      juniper: foo
   - include-filters: path/to/include/filter.yaml
```
where the filter.yaml file is a list of additional filters.
