### ISSUE TITLE
Generated ACLs for Cisco and CiscoNX targets are incorrectly generated as CiscoXR commands when using object-group

### ISSUE THREAD

**Issue by deep-blue-pulsar** [aerleon/aerleon#327]
I have the following def and pol files:

```yaml
networks:
  NET1:
    values:
      - address: 10.10.10.0/24
  NET2:
    values:
      - address: 10.10.20.0/24
services:
  HTTP:
    - protocol: tcp
      port: 80
  HTTPS:
    - protocol: tcp
      port: 443
  WEB:
    - HTTP
    - HTTPS
```

```yaml
filters:
  - header:
      targets:
        cisco: TEST_ACL_INBOUND object-group
    terms:
      - name: NET1-to-NET2-WEB
        source-address: NET1
        destination-address: NET2
        destination-port: WEB
        protocol: tcp
        action: accept
```
I have tested this policy with targets set to "cisco", "cisconx", "ciscoxr". These platforms have different syntax for object-group and ACL entries but Aerleon generates the same syntax for all 3:

```
object-group network ipv4 NET1
 10.10.10.0/24
exit

object-group network ipv4 NET2
 10.10.20.0/24
exit

object-group port 80-80
 eq 80
exit

object-group port 443-443
 eq 443
exit

no ipv4 access-list TEST_ACL_INBOUND
ipv4 access-list TEST_ACL_INBOUND

 remark NET1-to-NET2-WEB
 permit tcp net-group NET1 net-group NET2 port-group 80-80
 permit tcp net-group NET1 net-group NET2 port-group 443-443

exit

```

The expected output for each of the platforms should be:

```
# IOS-XE
object-group network NET1
 10.10.10.0 255.255.255.0

object-group network NET2
 10.10.20.0 255.255.255.0
!
object-group service WEB
 tcp 80
 tcp 443
!
ip access-list extended TEST_ACL_INBOUND
  permit object-group WEB object-group NET1 object-group NET2
!

# NX-OS
object-group ip address NET1
 10 10.10.10.0/24
!
object-group ip address NET2
 10 10.10.20.0/24
!
object-group ip port WEB
 10 eq 80
 20 eq 443
!
ip access-list TEST_ACL_INBOUND
  permit tcp addrgroup NET1 addrgroup NET2 portgroup WEB


# IOS-XR

object-group network ipv4 NET1
 10.10.10.0/24
object-group network ipv4 NET2
 10.10.20.0/24
object-group port WEB
 eq 80
 eq 443
!
ip access-list extended TEST_ACL_INBOUND
  permit tcp net-group NET1 net-group NET2 port-group WEB
!
```
You can see that the syntax for each platform is vastly different. 
The other issue I observed is that services are not being correctly grouped into the same object and the resulting configuration declares one group per port, resulting in multiple lines for a single rule which defeats the purpose of using object-groups.
