### ISSUE TITLE
Incorrect keyword value format, policies still generate ignoring the keyword.

### ISSUE THREAD

**Issue by sridsdale-godaddy** [aerleon/aerleon#337]
If the keyword values in a term are in the wrong format it can cause the keyword to be ignored and potentially dangerous policies to be generated. 

For example, someone changes this field in a term from:

`destination-port: ['SSH', 'HTTP', 'HTTPS']`

to

`destination-port: ['SSH', 'HTTP', 'HTTPS', 12345]`

```
filters:
 - header:
     comment: auto generated ACL - manual changes will be overwritten
     targets:
       juniper: inbound inet not-interface-specific
       cisco: inbound extended
   terms:
   - action: accept
     destination-port:
     - SSH
     - HTTP
     - HTTPS
     - 12345
     name: some-example-term
     protocol: tcp
```

Will log `WARNING:absl:Unrecognized value format for destination-port: ['SSH', 'HTTP', 'HTTPS', 12345]` but will then generate the policy and ignore the keyword/value pair in the term and generate (in this example the rather undesirable):

```
firewall {
    family inet {
        /*
         ** $Id:$
         ** $Date:$
         ** $Revision:$
         **
         ** auto generated ACL - manual changes will be overwritten
         */
        replace: filter inbound {
            term some-example-term {
                from {
                    protocol tcp;
                }
                then accept;
            }
        }
    }
}

! $Id:$
! $Date:$
! $Revision:$
no ip access-list extended inbound
ip access-list extended inbound
 remark $Id:$
 remark auto generated ACL - manual changes will be overwritten
 remark some-example-term
 permit tcp any any
exit
```

However, if the service token is passed as a string (not that I'm advocating anyone actually defines services as such, just an example!) I get an exception that the service is not defined (as expected).

`destination-port: ['SSH', 'HTTP', 'HTTPS', '12345']`

`<class 'aerleon.lib.naming.UndefinedServiceError'>`

In both instances the list of service definitions is invalid and it would be desirable if the policy didn't generate in either instance.

It's a wider question rather than just lists of services, if the keyword values are garbage, should the keyword be ignored in the term and have potentially dangerous policies generated or should it raise an exception? 

Someone making a typo in a keyword itself can also generate a policy when perhaps it shouldn't.
