### ISSUE TITLE
Juniper SRX dns-name fqdn address-book generated configuration missing suffix index number

### ISSUE THREAD

**Issue by jbotello7381** [aerleon/aerleon#345]
After testing aerleon srx dns-name support, notice the generated configuration was not correct.

`aerleon==1.6.0`

```
---
networks:
  Mgmt_Mgmt-Net_0:
    values:
      - address: 10.10.17.0/24
        comment:
  Mgmt_Mgmt-Net:
    values:
      - Mgmt_Mgmt-Net_0
  Pub_Mgmt-Name_0:
    values:
      - address: 99.99.98.0/23
        comment:
  Pub_Mgmt-Name_FQDN_0:
    values:
      - fqdn: pubtest1.jimbo.net
        comment: pubtest1
  Pub_Mgmt-Name_FQDN_1:
    values:
      - fqdn: pubtest2.jimbo.net
        comment: pubtest2
  Pub_Mgmt-Name:
    values:
      - Pub_Mgmt-Name_0
  Pub_Mgmt-Name_FQDN:
    values:
      - Pub_Mgmt-Name_FQDN_0
      - Pub_Mgmt-Name_FQDN_1
```

The following `networks.yaml` file after running aerleon config rendered generate the following output

```
        security-zone Pub {
            replace: address-book {
                address Pub_Mgmt-Name_0 99.99.98.0/23;
                address-set Pub_Mgmt-Name {
                    address Pub_Mgmt-Name_0;
                }
                address Pub_Mgmt-Name_FQDN_FQDN_0 {
                    dns-name pubtest1.jimbo.net;
                }
                address Pub_Mgmt-Name_FQDN_FQDN_0 {>>>>>> should be Pub_Mgmt-Name_FQDN_FQDN_1
                    dns-name pubtest2.jimbo.net;
                }
                address-set Pub_Mgmt-Name_FQDN_FQDN {
                    address Pub_Mgmt-Name_FQDN_FQDN_0;
                    address Pub_Mgmt-Name_FQDN_FQDN_1;
                }
            }
        }
```

after looking the code, there's a missing `counter += 1` inside the condition that generate the configuration on `junipersrx.py`

https://github.com/aerleon/aerleon/blob/18e6044ee6bc181fb08cdcb799bc634083840e9c/aerleon/lib/junipersrx.py#L703

```
    def _GenerateAddresses(self, token: str, ips, fqdns):
        target = IndentList(self.INDENT)
        counter = 0
        ips = nacaddr.SortAddrList(ips)
        ips = nacaddr.CollapseAddrList(ips)
        for ip in ips:
            target.IndentAppend(4, 'address ' + token + '_' + str(counter) + ' ' + str(ip) + ';')
            counter += 1
        for fqdn in fqdns:
            target.IndentAppend(4, f'address {token}_{counter} {{')
            target.IndentAppend(5, f'dns-name {fqdn.fqdn};')
            target.IndentAppend(4, f'}}')
            # counter += 1   After adding this line, the generated configuration match the yaml
        return target
```
        
output after adding the `counter +=1` line

```
        security-zone Pub {
            replace: address-book {
                address Pub_Mgmt-Name_0 99.99.98.0/23;
                address-set Pub_Mgmt-Name {
                    address Pub_Mgmt-Name_0;
                }
                address Pub_Mgmt-Name_FQDN_FQDN_0 {
                    dns-name pubtest1.jimbo.net;
                }
                address Pub_Mgmt-Name_FQDN_FQDN_1 {
                    dns-name pubtest2.jimbo.net;
                }
                address-set Pub_Mgmt-Name_FQDN_FQDN {
                    address Pub_Mgmt-Name_FQDN_FQDN_0;
                    address Pub_Mgmt-Name_FQDN_FQDN_1;
                }
            }
        }
```
