### ISSUE TITLE
Arista traffic-policy comma for multiple ports

### ISSUE THREAD

**Issue by dominik-michalina** [aerleon/aerleon#363]
Hello,

I've build Arista traffic policy with Aerleon which works great with just one issue. If there is multiple ports defined in services, the services must be separated by comma on Arista:

```
services:
  HTTP-HTTPS:
    - port: 80
      protocol: tcp
    - port: 443
      protocol: tcp
```

Output from Aerleon:
``` 
     match Allow-HTTP ipv4
         !! Allow HTTP inbound traffic
         destination prefix 10.10.10.0/24
         protocol tcp destination port 80 443
```
Configuration on the swith:
```
ASBR(config-s-1-traffic-policy-match-TP-WAN-IN-Allow-HTTP-ipv4)# protocol tcp destination port 80 443 ?
% Unrecognized command
ASBR(config-s-1-traffic-policy-match-TP-WAN-IN-Allow-HTTP-ipv4)# protocol tcp destination port 80,443 ?
  ,     extend list
  -     specify range
  <cr>
```
Could you please take a look at it?

Thank you.
Dominik
