### ISSUE TITLE
nftables generator omits ports

### ISSUE THREAD

**Issue by Pythoner6** [aerleon/aerleon#376]
Given the definitions:
```
networks:
  WEB_SERVERS:
    values:
      - address: 10.1.2.3
services:
  HTTPS:
    - protocol: tcp
      port: 443
```
And the policies:
```
filters:
  - header:
      comment: Example inbound
      targets:
        nftables: inet input
    terms:
      - name: accept-web-servers
        comment: Accept connections to our web servers.
        destination-address: WEB_SERVERS
        destination-port: HTTPS
        protocol: tcp
        action: accept
```

I expect `aclgen` to produce something like:
```
table ip filtering_policies {
    chain accept-web-servers {
        comment "Accept connections to our web servers."
        ip daddr 10.1.2.3/32 tcp dport 443 ct state new accept
    }
    chain root0 {
        comment "Example inbound"
        type filter hook input priority 0; policy drop;
        ct state established,related accept
        jump accept-web-servers
    }
}
```

However, with 1.9.0, I instead get a ruleset that completely ignores the port:

```
table ip filtering_policies {
    chain accept-web-servers {
        comment "Accept connections to our web servers."
        ip daddr 10.1.2.3/32 ip protocol tcp ct state new accept
    }
    chain root0 {
        comment "Example inbound"
        type filter hook input priority 0; policy drop;
        ct state established,related accept
        jump accept-web-servers
    }
}
```
