### ISSUE TITLE
NX-OS VRRP uses a protocol keyword that is not recognized

### ISSUE THREAD

**Issue by mf84** [aerleon/aerleon#380]
Using aerleon-1.9.0

And a term like:

```
filters:
  - header:
      targets:
        cisconx: vlan2506-in
    terms:
      - name: permit-vrrp
        destination-address: vrrp_mcast_net
        protocol: vrrp
        action: accept
```

The resulting file looks like this:

```
 remark permit-vrrp
 permit vrrp any host 224.0.0.18
```

The issue is, NX-OS does not recognize "vrrp" as a protocol name:

```
# configure session test
Config Session started, Session ID is 1
Enter configuration commands, one per line. End with CNTL/Z.
(config-s)# ip access-list vlan2506-in
(config-s-acl)# 85 permit vrr?
                                           ^
% Invalid number at '^' marker.
(config-s-acl)# 85 permit vrr
(config-s-acl)# 85 permit ?
  <0-255>  A protocol number
  ahp      Authentication header protocol
  eigrp    Cisco's EIGRP routing protocol
  esp      Encapsulation security payload
  gre      Cisco's GRE tunneling
  icmp     Internet Control Message Protocol
  igmp     Internet Group Management Protocol
  ip       Any IP protocol
  nos      KA9Q NOS compatible IP over IP tunneling
  ospf     OSPF routing protocol
  pcp      Payload compression protocol
  pim      Protocol independent multicast
  tcp      Transmission Control Protocol
  udf      User defined field match
  udp      User Datagram Protocol
```

This is  NXOS: version 9.3(11)

It should instead use the protocol number "112".
